name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exist
        run: |
          echo "Checking secrets availability..."

          if [ -n "${{ secrets.SUPABASE_URL }}" ]; then
            echo "✅ SUPABASE_URL is set"
            echo "Length: ${#SUPABASE_URL}"
          else
            echo "❌ SUPABASE_URL is NOT set"
          fi

          if [ -n "${{ secrets.SUPABASE_PUBLIC_KEY }}" ]; then
            echo "✅ SUPABASE_PUBLIC_KEY is set"
            echo "Length: ${#SUPABASE_PUBLIC_KEY}"
          else
            echo "❌ SUPABASE_PUBLIC_KEY is NOT set"
          fi

          if [ -n "${{ secrets.E2E_USERNAME_ID }}" ]; then
            echo "✅ E2E_USERNAME_ID is set"
          else
            echo "❌ E2E_USERNAME_ID is NOT set"
          fi

          if [ -n "${{ secrets.E2E_USERNAME }}" ]; then
            echo "✅ E2E_USERNAME is set"
          else
            echo "❌ E2E_USERNAME is NOT set"
          fi

          if [ -n "${{ secrets.E2E_PASSWORD }}" ]; then
            echo "✅ E2E_PASSWORD is set"
          else
            echo "❌ E2E_PASSWORD is NOT set"
          fi

          echo "All environment variables:"
          env | grep -E "(SUPABASE|E2E)" || echo "No matching env vars found"
