name: Security Scan

on:
  schedule:
    # Codziennie o 2:00 UTC
    - cron: '0 2 * * *'
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  # Skanowanie zależności
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level moderate

      - name: Upload npm audit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: npm-audit.json
          retention-days: 30

  # Skanowanie kodu
  code-scanning:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # Skanowanie tajemnic
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if BASE and HEAD are different
        id: check_commits
        run: |
          BASE_COMMIT=$(git rev-parse HEAD^)
          HEAD_COMMIT=$(git rev-parse HEAD)
          if [ "$BASE_COMMIT" = "$HEAD_COMMIT" ]; then
            echo "skip_trufflehog=true" >> $GITHUB_OUTPUT
            echo "No changes detected between commits. Skipping TruffleHog."
          else
            echo "skip_trufflehog=false" >> $GITHUB_OUTPUT
          fi

      - name: Run TruffleHog
        if: steps.check_commits.outputs.skip_trufflehog != 'true'
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          base: HEAD^
          head: ${{ github.sha }}
          extra_args: --only-verified --fail
